
spring:
  datasource:
    url: jdbc:h2:mem:coffeedb
    username: sa
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
